# Generated by Django 6.0 on 2026-01-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0002_client_owner_mailing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('failed', 'Не успешно')], max_length=20),
        ),
    ]
