# Generated by Django 6.0.1 on 2026-01-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_is_blocked_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
